--- #YAML:1.0
name:               MassSpec-ViewSpectrum
version:            0.08
abstract:           Perl extension for viewing a mass spectrum.
author:
    - Jonathan Epstein <Jonathan_Epstein@nih.gov>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    GD::Graph:  1.43
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
